### ISSUE TITLE
Outdated libraries

### ISSUE THREAD

**Issue by turowicz** [Azure-Samples/active-directory-b2c-python-flask-webapp#2]
I think the libraries referenced in the article may be out of date, it would be useful if there was a `requirements.txt` file added to exclude that possibility.

**Comment by Microshak** [comment]
Also Python 2 is going out of date January 1st 2020.  You Readme.md says this has only been tested in  Python 2.  Is there any plans to test in Python 3?

**Comment by jmprieur** [comment]
Thanks for the feedback. we archived the sample
cc: @parakhj
