### ISSUE TITLE
If response is None then calling response.get('error') will throw an error.

### ISSUE THREAD

**Issue by georgeslabreche** [Azure-Samples/active-directory-b2c-python-flask-webapp#3]
See here:

https://github.com/Azure-Samples/active-directory-b2c-python-flask-webapp/blob/7d2b7dead10b9db15854fcca57ab9ba715fba6b1/b2cflaskapp.py#L78-L82

Also, should probably be request.args.get instead of request.get.

**Comment by jmprieur** [comment]
Closing this issue as we archived the sample (See readme.md)
